export const PLATFORMS = [
  { id: 1, name: 'PC', slug: 'pc', iconUrl: '/images/icon/pc.png' },
  {
    id: 2,
    name: 'PlayStation',
    slug: 'playstation',
    iconUrl: '/images/icon/playstation.png',
  },
  { id: 3, name: 'Xbox', slug: 'xbox', iconUrl: '/images/icon/xbox.png' },
  { id: 4, name: 'iOS', slug: 'ios', iconUrl: '/images/icon/ios.png' },
  {
    id: 5,
    name: 'Apple Macintosh',
    slug: 'mac',
    iconUrl: '/images/icon/mac.png',
  },
  { id: 6, name: 'Linux', slug: 'linux', iconUrl: '/images/icon/linux.png' },
  {
    id: 7,
    name: 'Nintendo',
    slug: 'nintendo',
    iconUrl: '/images/icon/nintendo.png',
  },
  {
    id: 8,
    name: 'Android',
    slug: 'android',
    iconUrl: '/images/icon/android.png',
  },
  { id: 9, name: 'Atari', slug: 'atari', iconUrl: null },
  { id: 10, name: 'Commodore / Amiga', slug: 'commodore-amiga', iconUrl: null },
  { id: 11, name: 'SEGA', slug: 'sega', iconUrl: '/images/icon/sega.png' },
  { id: 12, name: '3DO', slug: '3do', iconUrl: null },
  { id: 13, name: 'Neo Geo', slug: 'neo-geo', iconUrl: null },
  { id: 14, name: 'Web', slug: 'web', iconUrl: '/images/icon/web.png' },
];
